name: Deploy application

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p ~/my-express-app/
            cd ~/my-express-app/
            git clone https://github.com/Bradleykingz/github-actions-tutorial app
            cd app
            ~/.nvm/versions/node/v12.14.0/bin/npm install
            ~/.nvm/versions/node/v12.14.0/bin/pm2 start app.js
